apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: default   # add if using Argo CD
spec:
  type: NodePort
  selector:
    app: hello
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30333
